@URL = http://localhost:81/api

##################### Login ################################
# @name login
POST {{URL}}/login
Content-Type: application/json

{
    "email": "customer@example.com",
    "password": "123456"
}
### 
@authToken = {{login.response.body.authorization.token}}

##################### Logout ################################
POST {{URL}}/logout
Content-Type: application/json
Authorization: Bearer {{authToken}}

