@URL = http://localhost:81/api

##################### Login ################################
# @name login
POST {{URL}}/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "123456"
}

### 
@authToken = {{login.response.body.authorization.token}}

##################### Get all order ################################

GET {{URL}}/order
Content-Type: application/json
Authorization: Bearer {{authToken}}

##################### Get Single ################################

GET {{URL}}/order/3
Content-Type: application/json
Authorization: Bearer {{authToken}}

##################### Add Order ################################
POST {{URL}}/order
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "status": "P",
    "details" : [{
        "product_id": 1,
        "quantity": 1,
        "unit_price": 1.5
    }]
}

##################### Update order ################################

PUT {{URL}}/order/3
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "status": "P",
    "details" : [
        {
            "product_id": 1,
            "quantity": 2,
            "unit_price": 1.5
        },
        {
            "product_id": 2,
            "quantity": 4,
            "unit_price": 1
        }
    ]
}

##################### Delete Order ################################
DELETE {{URL}}/order
Content-Type: application/json
Authorization: Bearer {{authToken}}
