@URL = http://localhost:81/api

### Login
# @name login
POST {{URL}}/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "123456"
}

### 
@authToken = {{login.response.body.authorization.token}}

##################### Get all policy ################################

GET {{URL}}/policy
Content-Type: application/json
Authorization: Bearer {{authToken}}

##################### Add a new policy ################################
POST {{URL}}/policy
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "role_id": 1,
    "resource_id": 1
}

##################### Edit policy ################################
PUT {{URL}}/policy/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "role_id": 1,
    "resource_id": 1
}


##################### Delete policy ################################
DELETE {{URL}}/policy/1
Content-Type: application/json
Authorization: Bearer {{authToken}}


