@URL = http://localhost:81/api/product
###

### Get all products
GET {{URL}}
Content-Type: application/json

### Get single product
GET {{URL}}/2
Content-Type: application/json


### Create new product
POST {{URL}}
Content-Type: application/json

{
    "name": "Table",
    "description": "A short description of the product",
    "price": 10.2,
    "quantity": 1
}


### Update a product
PATCH {{URL}}/2
Content-Type: application/json

{
    "name": "Table 2",
    "description": "A short description of the product",
    "price": 5.6,
    "quantity": 3
}


### Delete a product
DELETE {{URL}}/2
Content-Type: application/json


