@URL = http://localhost:81/api
###

##################### Login ################################
# @name login
POST {{URL}}/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "123456"
}

### 
@authToken = {{login.response.body.authorization.token}}


##################### Get All ################################
GET {{URL}}/product
Content-Type: application/json
Authorization: Bearer {{authToken}}


##################### Get ################################
GET {{URL}}/product/1
Content-Type: application/json


##################### Add ################################
POST {{URL}}/product
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Chair",
    "description": "A short description of the product",
    "price": 5.5,
    "quantity": 1
}


##################### Update ################################
PATCH {{URL}}/product/2
Content-Type: application/json

{
    "name": "Table",
    "description": "A short description of the product",
    "price": 5.6,
    "quantity": 3
}


##################### Delete ################################
DELETE {{URL}}/product/2
Content-Type: application/json
