@URL = http://localhost:81/api
###


##################### Login ################################
# @name login
POST {{URL}}/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "123456"
}

### 
@authToken = {{login.response.body.authorization.token}}

##################### Create User ################################
POST {{URL}}/register
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@example.com",
    "password": "123456",
    "role_id": "1"
}

##################### GET All users ################################
GET {{URL}}/user
Content-Type: application/json
Authorization: Bearer {{authToken}}


##################### Edit User ################################
PUT {{URL}}/user/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "admin",
    "email": "admin@example.com",
    "password": "123456"
}

##################### Delete User ################################
DELETE {{URL}}/user/1
Content-Type: application/json
Authorization: Bearer {{authToken}}